CREATE TABLE IF NOT EXISTS skaters (
    id UUID NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    avatar VARCHAR(1000) NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
    id UUID NOT NULL PRIMARY KEY,
    link VARCHAR(1000) NOT NULL,
    review VARCHAR(550),
    skaterId UUID
);

CREATE TABLE IF NOT EXISTS images (
    id UUID NOT NULL PRIMARY KEY,
    productId UUID NOT NULL,
    urlToImage VARCHAR(1000) NOT NULL
);

CREATE TABLE IF NOT EXISTS trickTips (
    id UUID NOT NULL PRIMARY KEY,
    trickTitle VARCHAR(100) NOT NULL UNIQUE,
    videoLink VARCHAR(1000) NOT NULL,
    tip VARCHAR(1000) NOT NULL
);